FTP_ADDRESS: 192.168.22.163
FTP_PASSWORD: 123456
FTP_PORT: 21
FTP_USERNAME: 1
#logging:
#    file: zjyl-web.log
#    level:
#        com:
#            cd:
#                zjyf:
#                    controller: DEBUG
#                    mapper: DEBUG
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mysql/*.xml

server:
    port: 8087
    tomcat:
        uri-encoding: UTF-8
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: zjphis
        url: jdbc:mysql://192.168.22.213/zj_ylws
        username: zjphis
    devtools:
        restart:
            enabled: false
    mvc:
        formcontent:
            putfilter:
                enabled: true
    application:
#        name: hzyf-new
        name: zjyf-screen
    redis:
        host: 192.168.22.221
        port: 6379
eureka:
    client:
        serviceUrl:
            defaultZone: http://192.168.22.223:7001/eureka/
    instance:
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
        prefer-ip-address: true
